# Generated by Django 5.1.2 on 2024-11-08 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_category_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
